// <auto-generated />
using System;
using FullTextSearch.API.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FullTextSearch.API.Migrations
{
    [DbContext(typeof(BookContext))]
    [Migration("20230706042929_initdb")]
    partial class initdb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FullTextSearch.API.Models.Book", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Book");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d93acb4e-0d55-42ed-9f1b-ccae83305d6d"),
                            Description = "Đây là một cuốn sách hay.",
                            Name = "Tôi tài giỏi, bạn cũng thế!"
                        },
                        new
                        {
                            Id = new Guid("bdb055c5-c7b3-4a4a-99b3-aaf421e82fdb"),
                            Description = "Một cuốn sách xuất sác.",
                            Name = "Thép đã tôi thế đấy!"
                        },
                        new
                        {
                            Id = new Guid("3c41b86e-4840-434b-aced-1c564ba15ab1"),
                            Description = "Nói về triết học khắc kỷ",
                            Name = "Chủ nghĩa khắc kỷ"
                        },
                        new
                        {
                            Id = new Guid("5849199d-d3d6-4f0b-a8a0-529acaec487b"),
                            Description = "Sách tình cảm",
                            Name = "Cuốn theo chiều gió"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
